# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# for testing all os platforms in our case for ubuntu, windows and macos

name: Java CI with Maven #name is optional

on: # required
  push:
    branches: ["main"] # name of the github event that triggers the workflow inn this case its master or main  when code  is pushed
  pull_request:
    branches: ["main"] # name of the github event that triggers the workflow  in our case its main or master when comeone makes pull request

jobs:
  build:
    # in yml ${{variable-name}} is used for declaring the variables in our case its matrix.os because we testing it for 3 os one after the other
    #    runs-on: ${{matrix.os}}    # when we want to test it on all the os platform
    #    strategy:
    #      matrix:
    #        os: [ubuntu-latest]

    runs-on: ubuntu-latest # when we want to test it in single os environment ubuntu

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17 # name is the name that we give for out action
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      # to build and push app to docker hub , first we should login to docker hub and then need to build and push
      - name: before building login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
          #password: ${{secrets.DOCKER_SECRET_TOKEN}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: build and push image to docker hub
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: praveenfc/tuckit_locker_back_github_action:3.10.11

    # docker for linux is pre-installed but for mac and windows we need to install it manually, so firstly testing it for linux
    #- name: generating a docker image and push it docker repository

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
#    - name: Update dependency graph
#      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
